### ISSUE TITLE
python problem

### ISSUE THREAD

**Issue by antony62110** [maxmillion18/Ogui#1]
Hello,
when I run the command, but an error me

C: \ Users \ emmanuelle \ Desktop \ agar server \ Ogui-master> python GUI.py
Traceback (most recent call last):
   File "GUI.py", line 316, in <module>
     app = App (master = root)
   File "GUI.py", line 24, in **init**
     self.crWid ()
   File "GUI.py", line 46, in crWid
     self.ocl = Comm.OgarTerm (self.console)
   File "C: \ Users \ emmanuelle \ Desktop \ agar server \ Ogui-master \ Comm.py", line 11,
in **init**
     self.ogarCL pexpect.spawn = ('node Ogar')
AttributeError: 'module' object Has No attribute 'spawn'

I'm on Windows 8.1 , Python34

Thank you

**Comment by mnurzia** [comment]
Hi @antony62110,

I think that the problem with python is caused by you not having the right dependencies. You should try installing pexpect with pip (for python) and see if it works.

**Comment by antony62110** [comment]
Hello,
after some modification.
and Python 2.7 installation,
I end up with a new error.

Traceback (most recent call last):
  File "gui.py", line 590, in <module>
    app = App(master=root)
  File "gui.py", line 302, in **init**
    self.config = Config.OgarConfig('gameserver.ini')
  File "C:\Users\emmanuelle\Music\Ogui-master\Config.py",
    self.config.read_string(self.contents)
  File "C:\Python27\lib\site-packages\configparser.py", l

```
sfile = io.StringIO(string)
```

TypeError: initial_value must be unicode or None, not str

Thank you

**Comment by mnurzia** [comment]
@antony62110 I think that the problem was not caused by your python version. Ogui works only with Python 3.4. I looked into this and found that when you download the zip file, Ogar does not download. Try downloading Ogar and placing it in the Ogui directory, (or placing your current Ogar into the Ogui directory) and then running it in Python 3.4.

**Comment by antony62110** [comment]
Thank you.
I reinstall python34.
but the error come back.

Ogui-master \ Comm.py ", line 11, in **init**
self.ogarCL pexpect.popen_spawn = ('node Ogar')
AttributeError: 'module' object Has No attribute 'popen_spawn'

after some research.
here's what I find.

Pexpect on Windows

New in version 4.0: Windows Support

Pexpect can be used on Windows to wait for a pattern to be produced by a child process, using pexpect.popen_spawn.PopenSpawn, gold has file descriptor, using pexpect.fdpexpect.fdspawn. This shoulds be regarded experimental for now.

pexpect.spawn and pexpect.run () are not available on Windows, Unix As They Rely on pseudoterminals (ptys). Cross platform code must not use thesis.

So pexpect.spawn was not compatible with Windows.
what can I do now.
thanks for your help.

**Comment by mnurzia** [comment]
@antony62110 I was not aware of this when I released Ogui. I don't have access to a Windows computer right now, and I will try to find an alternative to pexpect that works on Windows. Sorry.

**Comment by antony62110** [comment]
Thank you a lot.
here's an alternative to win pexpect pexpect.spawn
yet another mistake. pathlist string.split = (p, os.pathsep)
AttributeError: 'module' object Has No attribute 'split'
Thank you

**Comment by mnurzia** [comment]
I'm preparing a virtual machine with Windows so I can test these problems and hopefully fix them. I have looked into winpexpect and wexpect as alternatives to pexpect, so I will be starting with those.

**Comment by antony62110** [comment]
Thank you a lot.

I try the thing.
but still the same error.

C: \ Users \ emmanuelle \ Desktop \ Ogui-master> python gui.py
Traceback (most recent call last):
   File "gui.py", line 316, in <module>
     app = App (master = root)
   File "gui.py", line 24, in **init**
     self.crWid ()
   File "gui.py", line 46, in crWid
     self.ocl = Comm.OgarTerm (self.console)
   File "C: \ Users \ emmanuelle \ Desktop \ Ogui-master \ Comm.py", line 11, in **init**
     self.ogarCL pexpect.spawn = ('node Ogar')
   File "C: \ Python34 \ lib \ site-packages \ winpexpect-1.5-py3.4.egg \ pexpect.py" line
  429, in **init**
     self._spawn (command, args)
   File "C: \ Python34 \ lib \ site-packages \ winpexpect-1.5-py3.4.egg \ pexpect.py" line
  514, in _spawn
     command_with_path = which (self.command)
   File "C: \ Python34 \ lib \ site-packages \ winpexpect-1.5-py3.4.egg \ pexpect.py" line
  1782 in qui
     pathlist string.split = (p, os.pathsep)
AttributeError: 'module' object Has No attribute 'split'

**Comment by antony62110** [comment]
hello Maxmillion 18
you have news for windows.
Thank you

**Comment by antony62110** [comment]
Hi,
I managed to run the software but nothing appears.
http://www.hostingpics.net/viewer.php?id=384532python.png

![python](https://cloud.githubusercontent.com/assets/15252053/10832702/324e9542-7e8d-11e5-8f8b-cf20ccb83c16.PNG)
